### ISSUE TITLE
Possible missing file?

### ISSUE THREAD

**Issue by max-lancaster** [zmr/namsel#1]
I just cloned and configured an ubuntu VM using virtualbox and vagrant and when I tried to run the `./namsel.py preprocess ~/vagrant/white-lotus-garland/` where ~/vagrant/white-lotus-garland/ is the folder that contains my pdf I'm getting an error that appears to indicate a file called **_logistic-cls_** is missing from the original commits.  Here's the full error message:

Traceback (most recent call last):
  File "./namsel.py", line 8, in <module>
    from line_breaker import LineCluster, LineCut
  File "/vagrant/line_breaker.py", line 12, in <module>
    cls = load_cls('logistic-cls')
  File "/vagrant/classify.py", line 251, in load_cls
    return joblib.load(local_file(name))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 567, in load
    with open(filename, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/vagrant/logistic-cls'

**Comment by zmr** [comment]
logistic-cls and rbf-cls are generated by classify.py, which is setup and run by lines 9-17 in ubuntu_install.sh. The logistic-cls and rbf-cls classifiers are both necessary for namsel to run and take a while (up to an hour) to train.

**Comment by max-lancaster** [comment]
Hi @zmr thanks for getting back to me, I was able to work my way through several issues with ubuntu_install.sh on a fresh ubuntu / vagrant box as you can see in my [pull request](https://github.com/zmr/namsel/pull/2).  Now that everything seems to be installed successfully I'm getting the following message when running classify.py within ubuntu_install.sh:

`libdc1394 error: Failed to initialize libdc1394
loading training data
ubuntu_install.sh: line 20:  9179 Killed                  python classify.py`

`libdc1394 error: Failed to initialize libdc1394` appears to only be a warning as noted [here](http://stackoverflow.com/a/12689392/65187) so it appears that for some reason classify.py is aborting prematurely for some unknown reason.  Any help you can provide would be much appreciated since I am quite keen to start making use of your excellent work!
