### ISSUE TITLE
ubuntu_install.sh reports errors when ran on clean Ubuntu install

### ISSUE THREAD

**Issue by pavelaantonov** [zmr/namsel#10]
When running "ubuntu_install.sh" on clean Ubuntu 16.04.3 installation, following error messages are displayed at the end of install process:

```
Training the logistic regression classifier. This may take a while.
fitting the classifier
saving logistic regression cls to disk
/home/translator/namsel-master/accuracy_test.py:47: SyntaxWarning: name 'cls' is assigned to before global declaration
  global cls
Loading test data
importing classifier
{'warm_start': False, 'C': 1000, 'n_jobs': 1, 'verbose': 0, 'intercept_scaling': 100, 'fit_intercept': True, 'max_iter': 100, 'penalty': 'l2', 'multi_class': 'ovr', 'random_state': None, 'dual': False, 'tol': 0.0001, 'solver': 'liblinear', 'class_weight': None}
scoring ...
starting tests. this will take a moment
Traceback (most recent call last):
  File "classify.py", line 271, in <module>
    acc = test_all(clsf=cls)
  File "/home/translator/namsel-master/accuracy_test.py", line 75, in test_all
    test_accuracy(keys[0], clsf)
  File "/home/translator/namsel-master/accuracy_test.py", line 55, in test_accuracy
    x3.append(normalize_and_extract_features(j))
  File "/home/translator/namsel-master/feature_extraction.py", line 59, in normalize_and_extract_features
    return extract_features(newarr)
  File "/home/translator/namsel-master/feature_extraction.py", line 74, in extract_features
    raise ValueError, 'Scaler not defined'
ValueError: Scaler not defined

```

**Comment by eroux** [comment]
I'm getting the same error message on Debian 9

**Comment by groovybits** [comment]
This fixes it for me, it seems it needs the full path...

diff --git a/feature_extraction.py b/feature_extraction.py
index 6a86781..f32135b 100644
--- a/feature_extraction.py
+++ b/feature_extraction.py
@@ -11,7 +11,9 @@ from zernike_moments import zernike_features
 import os
 from utils import local_file

-SCALER_PATH = 'zernike_scaler-latest'
+#SCALER_PATH = 'zernike_scaler-latest'
+SCALER_PATH = '/home/bds108/namsel/zernike_scaler-latest'
+SCALER_DEFINED = False
 if os.path.exists(SCALER_PATH):
     scaler = joblib.load(local_file(SCALER_PATH))
     transform = scaler.transform

I didn't investigate enough yet to figure out how to pass the right PATH into it automatically :).
