### ISSUE TITLE
Exception (Array Type Mismatch) during recognision

### ISSUE THREAD

**Issue by pavelaantonov** [zmr/namsel#9]
Hello!

While trying to OCR a page by using latest version of code, I'm getting "ValueError: Expected 2D array, got 1D array instead". Pre-processing works fine. I am attaching zipped source file and detaled message log for your reference

[vol046_0008.tif.zip](https://github.com/zmr/namsel/files/1276585/vol046_0008.tif.zip)

```
user@vm:~/namsel/namsel-master$ ./namsel.py recognize-page --format=text ~/k16-ocr/Vol046/vol046_0008.tif 
ignoring all warnings
Setting page type as pecha
Traceback (most recent call last):
  File "./namsel.py", line 104, in recognize_page
    self.get_page_elements()
  File "./namsel.py", line 79, in get_page_elements
    clear_hr =  self.conf.get('clear_hr', False))
  File "/home/osboxes/namsel/namsel-master/page_elements2.py", line 201, in __init__
    prprob = predict_proba(features)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py", line 1336, in predict_proba
    return super(LogisticRegression, self)._predict_proba_lr(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 338, in _predict_proba_lr
    prob = self.decision_function(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 300, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 410, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[  4.79619484e+00   2.88060706e-01   3.67993758e+00  -1.59886094e+00
  -9.86445904e-01   1.50422906e+00  -1.54989619e-01  -1.65340219e+00
   4.94192211e-01   6.96771909e-01   3.99122042e-01   1.73062815e+00
   2.91463003e+00  -1.96579749e+00   3.77826652e-02  -1.29804059e+00
  -1.15107398e+00  -5.24038716e-01   1.94973262e+00  -2.51923189e-01
   3.92818934e-01  -1.25334464e+00  -6.90244659e-01  -1.12700896e+00
  -7.56529883e-01   4.87551541e-01  -2.37897628e-01   2.37692295e-03
  -5.43916742e-01  -8.27674076e-01   1.86474967e+00  -1.74599359e+00
   3.09791520e-01  -5.95665212e-01  -6.16347855e-01  -1.09569675e+00
  -1.63284146e+00  -5.25616362e-01  -1.38193613e-01  -1.60339512e+00
  -1.03535425e+00  -5.58358984e-01   1.18632442e-01  -1.17342769e+00
  -4.52312595e-01  -1.30970960e+00  -5.86124264e-02  -1.02771939e+00
   1.13025321e-01  -1.99177980e-01  -6.41878979e-01  -7.56798629e-01
  -4.17648623e-01  -7.44406897e-01  -6.05927357e-01   2.28818306e-01
   9.80648041e-01  -1.52592074e+00   9.45070454e-02  -1.18882345e+00
  -1.20231188e+00  -6.14131869e-01   5.83339524e-01  -8.69709878e-01
  -1.45570547e+00  -4.70485355e-01  -8.08019466e-01  -1.07687003e+00
  -4.46610149e-01  -4.68850500e-01   1.01801108e+00   3.75262821e-01
  -2.30817414e-01  -1.26280885e+00  -7.74704204e-03  -1.17408996e+00
   7.05996270e-02  -9.83088206e-02   5.61770736e-01  -1.03349137e+00
   4.56839617e-01  -7.53924522e-01  -1.15404356e+00  -1.20318929e+00
  -7.97894075e-01  -1.08886990e+00  -1.08259335e-01   1.71850883e+00
   1.25968832e+00   4.44709062e-01  -4.05141942e-01  -3.70185144e-01
  -3.58044027e-01  -8.53476245e-01  -1.03195020e+00  -1.06528479e+00
   1.09950774e-01   1.74888403e+00   2.21133068e+00  -2.10174812e-02
  -3.02218818e-01  -3.10433442e-01  -1.12304679e+00  -9.62412928e-01
  -1.04257597e+00  -1.76879589e+00  -1.24681254e+00  -8.25432733e-01
  -9.34817873e-03  -3.28020059e-01  -8.78346317e-01  -1.07451139e+00
  -9.31331317e-01  -8.50449658e-01  -9.34759561e-01  -7.60306508e-01
  -8.63782366e-01  -1.42230699e+00  -9.73836252e-01  -9.25124528e-01
  -8.16107445e-01  -8.23509224e-01  -8.44593596e-01  -2.72470968e-01
  -8.97580081e-01  -8.79709427e-01  -3.20423838e-01  -8.52957976e-01
  -7.13321626e-01  -6.75543837e-01  -4.55227314e-01  -5.49359904e-01
  -7.58398548e-01  -4.96792337e-01  -5.83327494e-01   7.78797308e-01
   9.58049441e-01   1.08747234e+00  -4.47765516e-01  -5.33522628e-01
  -6.13674054e-01  -1.09438163e+00  -1.07593119e+00  -1.11323704e+00
  -1.65135980e+00  -1.06121083e+00  -5.34832179e-01  -8.95347729e-01
  -3.51226824e-01  -3.87567446e-01  -1.03230875e+00  -1.01290289e+00
  -1.12925270e+00  -1.57130552e+00  -1.12920490e+00  -1.09120503e+00
  -1.09786856e+00  -9.17809694e-01  -9.80658956e-01  -1.41418419e+00
  -8.88343967e-01  -8.28325023e-01  -9.82991482e-01  -9.44849810e-01
  -9.14182675e-01  -1.15983696e+00  -1.09148998e+00  -1.10407898e+00
  -1.07500530e+00  -8.52327156e-01  -9.35959397e-01  -1.27189838e+00
  -1.12961458e+00  -1.02800593e+00  -1.59307111e+00  -8.29051738e-01
  -6.36307007e-01  -5.99630022e-01  -4.85746065e-01  -5.40461080e-01
  -6.13913807e-01  -5.48031072e-01  -5.07165200e-01  -6.73293733e-01
  -5.86043553e-01  -7.17532563e-01  -4.14017115e-01  -3.93332584e-01
  -3.85065286e-01   1.40150144e+00   1.41890757e+00   1.21544076e+00
   1.72165435e-01  -7.65168603e-01  -5.99575296e-01  -8.56171638e-01
  -4.16728439e-01  -4.08775869e-01  -7.60784138e-01  -7.62197716e-01
  -9.12449645e-01  -1.35270036e+00  -1.00739958e+00  -8.85924176e-01
  -8.85571995e-01  -7.79775074e-01  -8.66097134e-01  -1.18499392e+00
  -8.44674772e-01  -6.57612649e-01  -8.64200605e-01  -8.42136259e-01
  -8.93095615e-01  -1.34073106e+00  -1.14360213e+00  -1.04084360e+00
  -1.05816699e+00  -7.04983111e-01  -7.45288837e-01  -1.16942118e+00
  -1.06199795e+00  -9.33768872e-01  -1.40189215e+00  -7.55061494e-01
  -6.21819329e-01  -4.74193707e-01  -3.92396821e-01  -4.86743282e-01
  -5.78759723e-01  -4.27973586e-01  -3.84102384e-01  -5.58986825e-01
  -6.33481943e-01  -7.43484256e-01  -3.62169212e-01  -3.42458594e-01
  -3.48368361e-01   5.88335176e-01   2.41111581e+00   1.95350974e+00
   1.31762849e+00  -4.79318003e-01  -3.99237757e-01  -5.82684870e-01
  -3.39659539e-01  -3.38008964e-01  -5.25252596e-01  -5.18686464e-01
  -6.43175615e-01  -1.10986112e+00  -6.50550799e-01  -1.94305933e-01
   2.94219301e-01  -4.82123872e-01  -5.41534013e-01  -7.02414076e-01
  -6.20728285e-01  -5.51817200e-01  -6.81380826e-01  -5.56945714e-01
  -6.12272993e-01  -1.14682747e+00  -9.89912300e-01  -8.73167948e-01
  -1.02975773e+00  -5.96343576e-01  -7.07249282e-01  -9.07696163e-01
  -7.42535898e-01  -6.19765897e-01  -4.37040976e-01   6.55683022e-01
   9.81012471e-01   2.10859045e+00  -5.13427089e-01  -5.31183830e-01
  -7.37033873e-01  -4.97675964e-01  -4.59502855e-01   2.62045685e-01
  -5.83302969e-01  -6.53228615e-01  -3.60438875e-01  -5.52815696e-01
  -8.73189893e-01  -1.04146572e+00  -1.05848617e+00  -9.72077245e-01
  -9.57698150e-01  -9.92308435e-01  -1.02818685e+00  -1.06358005e+00
  -1.08920720e+00  -1.11791444e+00  -1.10378389e+00  -1.07916154e+00
  -1.01036759e+00  -9.70584732e-01  -8.92740691e-01  -8.63024178e-01
  -8.33296955e-01  -8.73440044e-01  -9.33753543e-01  -9.33739816e-01
  -9.30891977e-01  -9.21264625e-01  -8.66492920e-01  -8.59174610e-01
  -8.32559519e-01  -7.36579844e-01  -6.34069657e-01  -4.64447823e-01
  -3.24289039e-01  -1.99059420e-01   1.97307551e+00   1.25696160e+00
   8.72957020e-01   5.21670384e-01  -6.43730857e-02  -6.73179287e-01
  -1.09811062e+00  -1.24502061e+00  -1.30161083e+00  -1.46936040e+00
  -1.57513233e+00  -1.69800242e+00  -1.77572171e+00  -1.78912126e+00
  -1.76633947e+00  -1.70299411e+00  -1.67049203e+00  -1.65315886e+00
  -1.70521366e+00  -1.78331647e+00  -1.75128851e+00  -1.71092250e+00
  -1.61854642e+00  -1.40387584e+00  -1.26070844e+00  -1.04003182e+00
  -7.57502461e-01  -2.85951288e-01   3.07726078e-01   7.28540145e-01
   9.65639649e-01   1.18432973e+00].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
****************
No content captured for this image
Saving empty page to output
****************

```

**Comment by pavelaantonov** [comment]
Got these results after a clean install on empty Ubuntu 16.04 LTS

**Comment by pavelaantonov** [comment]
Running on pre-processed file results in same error:
[vol046_0008.tif.zip](https://github.com/zmr/namsel/files/1276743/vol046_0008.tif.zip)

user@vm:~/namsel/namsel-master$ ./namsel.py recognize-page --format=text ~/k16-ocr/Vol046/out/vol046_0008.tif 
ignoring all warnings
Setting page type as pecha
Traceback (most recent call last):
  File "./namsel.py", line 104, in recognize_page
    self.get_page_elements()
  File "./namsel.py", line 79, in get_page_elements
    clear_hr =  self.conf.get('clear_hr', False))
  File "/home/osboxes/namsel/namsel-master/page_elements2.py", line 201, in __init__
    prprob = predict_proba(features)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/logistic.py", line 1336, in predict_proba
    return super(LogisticRegression, self)._predict_proba_lr(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 338, in _predict_proba_lr
    prob = self.decision_function(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/linear_model/base.py", line 300, in decision_function
    X = check_array(X, accept_sparse='csr')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/validation.py", line 410, in check_array
    "if it contains a single sample.".format(array))
ValueError: Expected 2D array, got 1D array instead:
array=[  4.21351965e+00   6.99827964e-01   3.70190262e+00  -2.22452998e+00
  -4.05455589e-01   2.26334698e+00  -1.48617774e+00  -1.51842333e+00
  -9.72202050e-01   6.94601850e-01   1.73521627e+00   5.60660706e-01
   2.97852156e+00  -4.66188777e-01  -1.48329119e+00   2.25763926e-01
  -2.98145187e-02  -1.08549572e+00   5.88657681e-01  -8.79917795e-01
  -7.70348382e-01  -1.04594630e+00   2.26644535e-03   8.95410709e-02
  -4.35803797e-01   3.99678510e-02   1.37172230e-01  -5.08486130e-01
  -1.30548204e+00  -8.53479739e-01   1.92229045e+00  -4.17322906e-02
  -6.79159713e-01  -7.00381942e-01  -1.28445941e-01  -1.00770290e+00
  -5.17790740e-01  -1.08255873e+00  -1.21801556e+00  -1.66417444e+00
  -7.90515603e-01  -5.11856089e-01  -6.99786890e-01  -9.42719389e-01
  -1.57289778e-02  -5.25564614e-01   4.44850055e-01  -8.69486166e-01
  -3.37598751e-01  -9.04567587e-01  -8.61990370e-01  -1.53393234e+00
  -1.20443578e+00  -1.93585057e-01  -4.80670754e-01  -2.59993093e-01
   9.37884877e-01   1.90634991e-01  -2.23199971e-01  -5.84866168e-01
  -1.13368448e+00  -3.71645762e-01  -4.23536281e-01   1.49040551e-01
  -8.86634644e-01  -1.29351802e+00  -1.75149677e+00  -1.32916881e+00
  -3.15983770e-01  -4.04389485e-01  -2.29307985e-01  -4.64121192e-02
  -4.85614567e-01  -1.16851780e+00  -7.05424737e-02  -1.21451070e+00
  -1.73400029e-01   3.80995518e-02  -9.49548832e-01   8.07937487e-01
  -2.21830498e-01  -1.62525081e+00  -1.81364764e+00  -1.57781098e+00
  -8.74589534e-01  -1.81854430e+00  -8.27488269e-01  -5.19557344e-01
   2.06387645e-01   1.50479601e-02  -4.05141942e-01  -3.70185144e-01
  -3.58044027e-01  -8.53476245e-01  -1.03195020e+00  -1.06528479e+00
   1.09950774e-01   1.74888403e+00   2.21133068e+00  -2.10174812e-02
  -3.02218818e-01  -3.10433442e-01  -1.12304679e+00  -9.62412928e-01
  -1.04257597e+00  -1.76879589e+00  -1.24681254e+00  -8.25432733e-01
  -9.34817873e-03  -3.28020059e-01  -8.78346317e-01  -1.07451139e+00
  -9.31331317e-01  -8.50449658e-01  -9.34759561e-01  -7.60306508e-01
  -8.63782366e-01  -1.42230699e+00  -9.73836252e-01  -9.25124528e-01
  -8.16107445e-01  -8.23509224e-01  -8.44593596e-01  -2.72470968e-01
  -8.97580081e-01  -8.79709427e-01  -3.20423838e-01  -8.52957976e-01
  -7.13321626e-01  -6.75543837e-01  -4.55227314e-01  -5.49359904e-01
  -7.58398548e-01  -4.96792337e-01  -5.83327494e-01   7.78797308e-01
   9.58049441e-01   1.08747234e+00  -4.47765516e-01  -5.33522628e-01
  -6.13674054e-01  -1.09438163e+00  -1.07593119e+00  -1.11323704e+00
  -1.65135980e+00  -1.06121083e+00  -5.34832179e-01  -8.95347729e-01
  -3.51226824e-01  -3.87567446e-01  -1.03230875e+00  -1.01290289e+00
  -1.12925270e+00  -1.57130552e+00  -1.12920490e+00  -1.09120503e+00
  -1.09786856e+00  -9.17809694e-01  -9.80658956e-01  -1.41418419e+00
  -8.88343967e-01  -8.28325023e-01  -9.82991482e-01  -9.44849810e-01
  -9.14182675e-01  -1.15983696e+00  -1.09148998e+00  -1.10407898e+00
  -1.07500530e+00  -8.52327156e-01  -9.35959397e-01  -1.27189838e+00
  -1.12961458e+00  -1.02800593e+00  -1.59307111e+00  -8.29051738e-01
  -6.36307007e-01  -5.99630022e-01  -4.85746065e-01  -5.40461080e-01
  -6.13913807e-01  -5.48031072e-01  -5.07165200e-01  -6.73293733e-01
  -5.86043553e-01  -7.17532563e-01  -4.14017115e-01  -3.93332584e-01
  -3.85065286e-01   2.08882419e+00   3.56261507e+00   3.19344248e+00
  -1.95101759e-01  -7.65168603e-01  -5.99575296e-01  -8.56171638e-01
  -4.16728439e-01  -4.08775869e-01  -7.60784138e-01  -7.62197716e-01
  -9.12449645e-01  -1.35270036e+00  -1.00739958e+00  -8.85924176e-01
  -8.85571995e-01  -7.79775074e-01  -8.66097134e-01  -1.18499392e+00
  -8.44674772e-01  -6.57612649e-01  -8.64200605e-01  -8.42136259e-01
  -8.93095615e-01  -1.34073106e+00  -1.14360213e+00  -1.04084360e+00
  -1.05816699e+00  -7.04983111e-01  -7.45288837e-01  -1.16942118e+00
  -1.06199795e+00  -9.33768872e-01  -1.40189215e+00  -4.66321066e-01
   1.18527311e-01   9.71555077e-01  -3.92396821e-01  -4.86743282e-01
  -5.78759723e-01  -4.27973586e-01  -3.84102384e-01  -5.58986825e-01
  -6.33481943e-01  -7.43484256e-01  -3.62169212e-01  -3.42458594e-01
  -3.48368361e-01  -3.29964972e-02   9.74932281e-01   8.74822194e-01
  -2.79034443e-01  -4.79318003e-01  -3.99237757e-01  -5.82684870e-01
  -3.39659539e-01  -3.38008964e-01  -5.25252596e-01  -5.18686464e-01
  -6.43175615e-01  -4.97178435e-01   1.40474917e+00   2.16155471e+00
   2.02675874e+00  -4.82123872e-01  -5.41534013e-01  -7.02414076e-01
  -6.20728285e-01  -5.51817200e-01  -1.46580752e-02  -1.85125131e-01
  -4.22641320e-01  -1.14682747e+00  -9.89912300e-01  -8.73167948e-01
  -1.02975773e+00  -5.96343576e-01  -7.07249282e-01  -9.07696163e-01
  -7.42535898e-01  -6.19765897e-01  -2.69907920e-01   2.82200003e+00
   3.46379825e+00   2.56480992e+00  -5.13427089e-01  -5.31183830e-01
  -7.37033873e-01  -4.97675964e-01  -4.59502855e-01   2.62045685e-01
  -5.83302969e-01  -6.53228615e-01  -3.60438875e-01  -5.52815696e-01
  -8.73189893e-01  -1.04146572e+00  -1.05848617e+00  -9.72077245e-01
  -9.57698150e-01  -9.92308435e-01  -1.02818685e+00  -1.06358005e+00
  -1.08920720e+00  -1.11791444e+00  -1.10378389e+00  -1.07916154e+00
  -1.01036759e+00  -9.70584732e-01  -8.92740691e-01  -8.63024178e-01
  -8.33296955e-01  -8.73440044e-01  -9.33753543e-01  -9.33739816e-01
  -9.30891977e-01  -9.21264625e-01  -8.66492920e-01  -8.59174610e-01
  -8.32559519e-01  -7.36579844e-01  -6.34069657e-01  -4.64447823e-01
  -3.24289039e-01  -1.99059420e-01   1.97307551e+00   1.25696160e+00
   8.72957020e-01   5.21670384e-01  -6.43730857e-02  -6.73179287e-01
  -1.09811062e+00  -1.24502061e+00  -1.30161083e+00  -1.46936040e+00
  -1.57513233e+00  -1.69800242e+00  -1.77572171e+00  -1.78912126e+00
  -1.76633947e+00  -1.70299411e+00  -1.67049203e+00  -1.65315886e+00
  -1.70521366e+00  -1.78331647e+00  -1.75128851e+00  -1.71092250e+00
  -1.61854642e+00  -1.40387584e+00  -1.26070844e+00  -1.04003182e+00
  -7.57502461e-01  -2.85951288e-01   3.07726078e-01   7.28540145e-01
   9.65639649e-01   1.18432973e+00].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
****************
No content captured for this image
Saving empty page to output
****************

**Comment by thubtenrigzin** [comment]
The new version 0.19.1 of scikit-learn seems to not work with namsel...
Try to downgrade the scikit-learn version to 0.18.1. That makes my installation of namsel work on a fresh ubuntu 16.04 LTS

You can use that command line:
sudo pip install --user --upgrade scikit-learn==0.18.1

All the best!

**Comment by groovybits** [comment]
I found adding [] around the features array got me past this issue...

File "/home/osboxes/namsel/namsel-master/page_elements2.py", line 201, in __init__
    prprob = predict_proba([features])

Although it seems odd so I am wondering what the real issue is and side effects of adding the [] around the features array is. 

Should we use 14.04 Ubuntu, I am going to try that version and see if it changes things. I would love to know the right way to handle this since it seems odd that features as an array changed between versions on how it behaves in the scikit-learn API (which I don't see any changes there in how it behaves for the input to the predict_proba() function).
